 1 name: Markdown Linting
  2 run-name: ${{ github.actor }} is running the linter.
  3 on: [push, pull_request]  
  4 jobs:
  5   Lint-Markdown:
  6     runs-on: ubuntu-latest
  7     steps:
  8       - uses: actions/checkout@v3
  9       - uses: DavidAnson/markdownlint-cli2-action@v9
 10         with:
 11           globs: '**/*.md'
